### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by Liaoer** [ericjjj/vms#1]
ERROR in ./src/stores/api.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../config in /Users/liao/Downloads/vms-master/frontend/src/stores
 @ ./src/stores/api.js 8:14-34

ERROR in ./src/tools/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../config.js in /Users/liao/Downloads/vms-master/frontend/src/tools
 @ ./src/tools/index.js 15:14-37

**Comment by ericjjj** [comment]
需要复制一下config.simple.js   .到 config.js
