### ISSUE TITLE
mongodb如果有密码该咋配置

### ISSUE THREAD

**Issue by cuiyongjian** [ericjjj/vms#11]

**Comment by cuiyongjian** [comment]
好像在config.js里并没有看到设置账户、密码的地方

**Comment by ericjjj** [comment]
啊 你可增加账号密码的字段 然后在这个文件中配置 https://github.com/ericjjj/vms/blob/master/backend/models/index.js

**Comment by cuiyongjian** [comment]
@ericjjj 这样会不会有点入侵业务代码了 ^_^

**Comment by ericjjj** [comment]
@cuiyongjian 会有入侵, 可以考虑 单独做 connect.js 的文件, 把数据库连接独立出去
