### ISSUE TITLE
测试环境登录报错，Provisional headers are shown

### ISSUE THREAD

**Issue by cassieLuo** [ericjjj/vms#12]

**Comment by iShawnWang** [comment]
打开页面上面显示 `Error: Network Error` 提示消息 !

**Comment by ericjjj** [comment]
啊? @iShawnWang @cassieLuo  可以给我看下 log 日志么

**Comment by ericjjj** [comment]
方便的话来个截图

**Comment by iShawnWang** [comment]
# 打开网页 : 
![2017-07-28 00 06 19](https://user-images.githubusercontent.com/20266594/28680347-a9eac99a-7328-11e7-966e-83600b028b49.png)

# 点登陆 : 
![2017-07-28 00 06 24](https://user-images.githubusercontent.com/20266594/28680374-bd58eb92-7328-11e7-9419-0800a109ea8d.png)

日志什么的我要怎么获取 ?

**Comment by ericjjj** [comment]
@iShawnWang backend 程序运行的日志

**Comment by ericjjj** [comment]
上面这些看不出来有什么问题

**Comment by ericjjj** [comment]
很有可能是 backend 运行失败

**Comment by iShawnWang** [comment]
我是打开  Demo : `http://vms.ericjj.com/login` 出现上面的问题, 我也拿不到日志吖... ~

**Comment by ericjjj** [comment]
@iShawnWang  😂实在抱歉 我以为你是在本地运行, 因为我把后端项目停掉了, 你可以在本地运行

**Comment by ericjjj** [comment]
闲下来会更新下 @iShawnWang 你可以关注这个项目 https://github.com/GeekPark/gpk_admin 完整度比较高
