### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by wd2010** [ericjjj/vms#3]

**Comment by ericjjj** [comment]
fixed

**Comment by ericjjj** [comment]
请再次尝试一下, 谢谢啦

**Comment by wd2010** [comment]
好的，谢谢！

**Comment by TerryZwei** [comment]
还是登陆不了~

**Comment by ericjjj** [comment]
@TerryZwei  抱歉, 不是登录不了 是有人登录了 然后把用户删除了 😅, 我把 api 修改一下 , 增加了
`API 是可以用的, 请不要删除用户 谢谢啦!😀` 提醒, 这样就可以正常访问了
