### ISSUE TITLE
请问一下如何在写Nodejs 代码的时候 使用import, export 语法?

### ISSUE THREAD

**Issue by xrr2016** [ericjjj/vms#4]
我已经安装了 babel-register babel-core babel-preset-2015 babel-preset-env ,
在入口文件开始 写了
```javascript
require('babel-register')
require("babel-polyfill")
```
以及在目录下添加了 .babelrc 文件
然而依然报 Unexpected token import 错误...
求解,谢谢.

**Comment by ericjjj** [comment]
是这样的, 同学 

在 [ index.js](https://github.com/ericjjj/vms/blob/master/backend/index.js) 里面写 
``` js
require('babel-register')
require("babel-polyfill")
```

然后逻辑代码 写在 server.js 等其他文件里,  启动文件不能用 es6

**Comment by ericjjj** [comment]
两个文件分开, 不知道这样解释的清楚么

**Comment by xrr2016** [comment]
原来是要分开啊, 知道了, 谢谢

**Comment by ericjjj** [comment]
对的,  希望能帮到你 😀
