### ISSUE TITLE
我把项目clone下来之后，不知道哪里注册用户，默认的123454321@qq.com登录不上

### ISSUE THREAD

**Issue by wh-Coder** [ericjjj/vms#5]

**Comment by wh-Coder** [comment]
报的错是：
OPTIONS http://127.0.0.1:3000/api/admin/account/login net::ERR_CONNECTION_REFUSED

我看了看我后端 node index 监听的接口是10000

不知道在哪里更改配置，让var isDev = process.env.NODE_ENV === 'dev';返回true

**Comment by wh-Coder** [comment]
我尝试在package.json修改 “script”的“dev”为“set NODE_ENV=dev && node index.js”

然后运行npm run dev 还是监听的10000，目前还是不知道怎么监听到3000

**Comment by wh-Coder** [comment]
暂时在utils/config.js中直接把var isDev = true

希望前辈指出正确的配置方式

**Comment by ericjjj** [comment]
抱歉 readme 已修改  应该是 `NODE_ENV=dev node index.js`

**Comment by ericjjj** [comment]
加上环境变量`NODE_ENV=dev`就行了 端口是根据这个来判断的

**Comment by wh-Coder** [comment]
@ericjjj 
![qq 20170414085649](https://cloud.githubusercontent.com/assets/26110097/25029671/fed0edd8-20f1-11e7-8626-56df3013e1a1.png)




还是没能配成功，不知道是哪里的问题

**Comment by ericjjj** [comment]
NODE_ENV=dev node index.js

**Comment by ericjjj** [comment]
去掉&&

**Comment by wh-Coder** [comment]
@ericjjj 
![qq 20170414093330](https://cloud.githubusercontent.com/assets/26110097/25030145/ab5029cc-20f5-11e7-9b5f-bf0bb0800bc6.png)

一样，
&& 这个只是连接两个语句
cross-env 是兼容mac和win

**Comment by ericjjj** [comment]
抱歉， config.js  应该是===dev  不是development   我缩写了

**Comment by ericjjj** [comment]
没对应上

**Comment by wh-Coder** [comment]
都弄清楚了
backend/utils/config.js
```
var isDev = process.env.NODE_ENV === 'dev';
console.log(process.env.NODE_ENV);
console.log(isDev)
```
总结一下
1） NODE_ENV=dev node index.js	    Windows下'NODE_ENV' 不是内部或外部命令
2） set NODE_ENV=dev node index.js   等效于 set NODE_ENV="dev node index.js"
3） set NODE_ENV=dev &&  node index.js 
	这个最奇怪：打印为process.env.NODE_ENV=dev   isDev=false
4）使用插件cross-env
	cross-env NODE_ENV=dev && node index.js
	结果和 3）一样
	cross-env NODE_ENV=dev node index.js	正确
5） 最后说一种就是把两条命令分开，也可以

**Comment by ericjjj** [comment]
😂 不友好的 windows 如果没有问题的话 我就关掉了 issue
